FROM node:20-alpine AS builder

WORKDIR /app

ARG VITE_API_URL
RUN test -n "$VITE_API_URL"
ENV VITE_API_URL=$VITE_API_URL

COPY frontend/package*.json ./
RUN npm install

COPY frontend /app
RUN npm run build

FROM nginx:alpine AS runtime

COPY infra/nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
